---
    - name: Install Python
      ansible.builtin.dnf:
        name:
         - python3
         - python3-pip
         - python3-PyMySQL
         - python3-packaging
           #    - python3-venv
        state: present

    - name: Install Flask & MySQL Connector
      ansible.builtin.pip:
        name:
         - flask
         - flask-mysql
         - cryptography
        extra_args: --break-system-packages
